homepage:
    pattern:  /
    defaults: { _controller: AcmeStoreBundle:Default:index }

create:
  pattern: /create/
  defaults: { _controller: AcmeStoreBundle:Default:create }

update:
  pattern: /update/
  defaults: { _controller: AcmeStoreBundle:Default:update }
  
delete:
  pattern: /delete/
  defaults: { _controller: AcmeStoreBundle:Default:delete }

createProduct:
  pattern: /createProduct/
  defaults: { _controller: AcmeStoreBundle:Default:createProduct }